name: PR Test

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get Pr Number
    - uses: jwalton/gh-find-current-pr@v1
      id: findPr
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Trigger Build
    - uses: Fishwaldo/webhook-action@master  
      env:
        BBSERVER: bamboo.my-ho.st
        BBUSER: ${{ secrets.bamboouser }}
        BBPASS: ${{ secrets.bamboopass }
        BBPRJ: OZW-PRTST
        PPPR: ${{ steps.findPr.outputs.pr }}
