name: PR Test

on: 
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Trigger Build
      uses: Fishwaldo/webhook-action@master  
      env:
        BBSERVER: bamboo.my-ho.st
        BBUSER: ${{ secrets.bamboouser }}
        BBPASS: ${{ secrets.bamboopass }}
        BBPRJ: OZW-PRTST
        BBPR: ${{ github.event.number }}
